services:
  - type: web
    name: job-tracker-api
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://job-tracker-sand-five-83.vercel.app
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
